[package]
name = "restop"
version = "0.0.1-241031"
authors = ["aeghn <aeghn@outlook.com>"]
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
debug = true
incremental = true

[dependencies]
process-data = { path = "lib/process_data" }
glob = { version = "0.3.3" }
regex = "1.11.2"
sysconf = "0.3.4"
nvml-wrapper = "0.11.0"
nix = { version = "0.30.1", default-features = false, features = [
    "signal",
    "fs",
] }
serde = { version = "1.0.219", features = ["serde_derive"] }
once_cell = "1.21.3"
hashbrown = "0.15.5"
num_cpus = "1.17.0"
chrono = "0.4.38"
log = "0.4.27"

bitflags = "2.9.3"
chin-tools = { path = "./lib/chin-tools/crates/chin-tools" }
chin-terminal-utils = { path = "./lib/chin-tools/crates/chin-terminal-utils" }
anyhow = "1.0.99"
crossterm = { version = "0.29.0", features = ["event-stream"] }
itertools = "0.14.0"
flume = { version = "0.11.0", default-features = false, features = ["async"] }
ratatui = { version = "0.29.0", features = [] }
append-only-vec = "0.1.4"
libc = "0.2.155"
unicode-width = "0.2.0"
